### ISSUE TITLE
Another memory leak

### ISSUE THREAD

**Issue by rwrx** [lostzen/lost#197] opened 2017-05-12 19:58 UTC
I have noticed that you got rid of some memory leaks in Lost. I have updated Mapzen Android SDK to latest version (I am using directly Git master version not compiled library from Maven) and tried whether memory leaks are not present, but unfortunately there is occurring another memory leak. I am sending screenshot from LeakCanary library which I am using in my app:

![another-memory-leak](https://cloud.githubusercontent.com/assets/2378743/26014719/25205186-375e-11e7-88f8-0b25dda9ece9.png)

**Comment by msmollin** [comment] 2017-05-12 20:09
Woohoo, haha! Thanks for the report.

What commit did you compile and run this against out of curiosity? We did just merge a PR today that dealt with some of this and pulled the latest snapshot of LOST in -
 https://github.com/mapzen/android/pull/368

**Comment by rwrx** [comment] 2017-05-12 20:16
It is this lastest commit to master branch: https://github.com/mapzen/android/commit/ad7898be5ab5815900cf7572639e00cff1a3aa9d . Hope this helps :).

**Comment by sarahlensing** [comment] 2017-05-19 22:04
@rwrx Thanks for your report! Could you repost the LeakCanary screenshot? It looks like it has been removed in the link above?

**Comment by sarahlensing** [comment] 2017-05-23 00:09
Thank you for the report @rwrx !

I am able to reproduce something similar if I remove the call to unregister `listener` in the sample app's `MultipleLocationListenerSingleClientActivity` class. Can you verify that you have not forgotten to unregister a listener in your app?

![screenshot_20170522-175512](https://cloud.githubusercontent.com/assets/494323/26333232/4d2a4b56-3f19-11e7-850f-2c1bdcb090ec.png)

On a related note, while debugging this issue, I discovered that we don't provide a way to unregister `ConnectionCallbacks` which resulted in [this PR](https://github.com/mapzen/lost/pull/208)

**Comment by rwrx** [comment] 2017-05-23 17:35
Thank you for response and for trying it. Yes, I have there a call to `LocationServices.FusedLocationApi.removeLocationUpdates()`. But now I have realized that `LocationServices.FusedLocationApi.requestLocationUpdates` may be called more than once for a single object. Couldn't this be a problem? Or should that HashMap handle this? 

Also from my screenshot there is no instance of some of classes from my app, besides that leaked MainActivity instance. So I assume that this is going from Mapzen Android SDK not from Lost itself. What do you think? Maybe I should post this to Mapezn Android SDK issues, but I didn't realized it before.

**Comment by msmollin** [comment] 2023-04-23 14:14
Closing as this repo is no longer maintained.

**Closed by msmollin** 2023-04-23 14:14 UTC
